use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc, Weak,
};

use async_trait::async_trait;
use parking_lot::Mutex;
use tokio::sync::broadcast::{self, Receiver, Sender};

use crate::{error::TransportError, message::Message};

/// Events generated by transports and delivered to peers.
#[derive(Debug, Clone)]
pub enum TransportEvent {
    Closed,
    Message(Message),
}

pub type TransportEventReceiver = Receiver<TransportEvent>;

/// Abstraction representing the communication channel used by peers.
#[async_trait]
pub trait Transport: Send + Sync {
    /// Send a message through the transport.
    async fn send(&self, message: Message) -> Result<(), TransportError>;
    /// Close the transport.
    fn close(&self);
    /// Whether the transport is already closed.
    fn is_closed(&self) -> bool;
    /// Subscribe to transport events.
    fn subscribe(&self) -> TransportEventReceiver;
}

/// Simple in-memory transport used for testing and unit exercising.
#[derive(Clone)]
pub struct InMemoryTransport {
    inner: Arc<InMemoryTransportInner>,
}

struct InMemoryTransportInner {
    closed: AtomicBool,
    events: Sender<TransportEvent>,
    peer: Mutex<Option<Weak<InMemoryTransportInner>>>,
}

impl InMemoryTransport {
    /// Create a pair of transports connected to each other.
    pub fn pair() -> (Self, Self) {
        let (left_tx, _) = broadcast::channel(16);
        let (right_tx, _) = broadcast::channel(16);

        let left_inner = Arc::new(InMemoryTransportInner {
            closed: AtomicBool::new(false),
            events: left_tx,
            peer: Mutex::new(None),
        });

        let right_inner = Arc::new(InMemoryTransportInner {
            closed: AtomicBool::new(false),
            events: right_tx,
            peer: Mutex::new(None),
        });

        *left_inner.peer.lock() = Some(Arc::downgrade(&right_inner));
        *right_inner.peer.lock() = Some(Arc::downgrade(&left_inner));

        (Self { inner: left_inner }, Self { inner: right_inner })
    }

    fn deliver_to_peer(&self, message: Message) -> Result<(), TransportError> {
        let peer = self
            .inner
            .peer
            .lock()
            .as_ref()
            .and_then(|peer| peer.upgrade())
            .ok_or_else(|| TransportError::Failure("peer transport missing".into()))?;

        if peer.closed.load(Ordering::SeqCst) {
            return Err(TransportError::Closed);
        }

        peer.events
            .send(TransportEvent::Message(message))
            .map_err(|error| TransportError::Failure(error.to_string()))?;

        Ok(())
    }

    fn notify_peer_closed(&self) {
        if let Some(peer) = self
            .inner
            .peer
            .lock()
            .as_ref()
            .and_then(|peer| peer.upgrade())
        {
            let _ = peer.events.send(TransportEvent::Closed);
        }
    }
}

#[async_trait]
impl Transport for InMemoryTransport {
    async fn send(&self, message: Message) -> Result<(), TransportError> {
        if self.inner.closed.load(Ordering::SeqCst) {
            return Err(TransportError::Closed);
        }

        self.deliver_to_peer(message)
    }

    fn close(&self) {
        if self.inner.closed.swap(true, Ordering::SeqCst) {
            return;
        }

        let _ = self.inner.events.send(TransportEvent::Closed);
        self.notify_peer_closed();
    }

    fn is_closed(&self) -> bool {
        self.inner.closed.load(Ordering::SeqCst)
    }

    fn subscribe(&self) -> TransportEventReceiver {
        self.inner.events.subscribe()
    }
}
